// Generated by CoffeeScript 1.7.1
(function() {
  (function(global) {
    return module.exports = {
      run: function() {
        var pkg;
        pkg = require("../../package.json");
        console.log("v" + pkg.version);
        return this;
      }
    };
  })(global);

}).call(this);
